import Home from './Home'
import Profile from './Profile'
import Events from './Events'
import Splash from './Splash'
import Settings from './Settings'
import Progress from './Progress'
import EventsDetail from './EventsDetail'
import Search from './Search'
import Teams from './Teams'
import Post from './Post'
import PostDetail from './PostDetail'
import PostEdit from './PostEdit'
import Login from './Login'
import Register from './Register'

export { Splash, Progress, Profile,Search, Home, Settings,Post,Events,EventsDetail,Teams,PostDetail,PostEdit,Login,Register}